### ISSUE TITLE
Where to find the output plugin zip to install it in IDE?

### ISSUE THREAD

**Issue by kiranpuppala** [ermattt/clij2k#1]
The final plugin output zip is missing. Also cannot find this plugin in the market place.

**Comment by ravibhojwani86** [comment]
@ermattt  having following issues with clij2k:

1. Unable to build the plugin as its not a gradle project and hence cannot run ./gradlew buildPlugin
2. PROJECT_PATH in command is a bit confusing here as it also refers to PROJECT_PATH/java/com/facebook/tools/intellij/kotlinator/resources/profiles/Kotlinator_Inspection_Profile.xml.
Infact tried creating a new plugin project and copied code fro this but it fails with some weird errors

@kiranpuppala  I believe you were able to run through this, can you please help here?
